language: python
python:
  - "2.7"
  - "pypy"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
sudo: false
dist: xenial
jobs:
  include:
    - python: "2.6"
      dist: trusty
    - python: "3.2"
      dist: trusty
    - python: "3.3"
      dist: trusty
install:
  - |
        if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then
           pip install coveralls
        fi
  - pip install protobuf
  - pip install pycodestyle
script:
  - make -C tools/python metaclean
  - make -C tools/python test
  - make -C tools/python lint
  - |
      # Check re-generation didn't change anything (except locale.py)
      git checkout --  python/phonenumbers/geodata/locale.py
      status=$(git status --porcelain ) || :
      if [[ -n ${status} ]]; then
        echo "Regenerated files differ from checked-in versions: ${status}"
        git status
        exit 1
      fi
  - |
        if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then
           cd python
           COVERAGE_FILE=main.cov coverage run --source=phonenumbers ./testwrapper.py
           COVERAGE_FILE=pb2.cov coverage run --source=phonenumbers.pb2 ./testpb2.py
           coverage combine main.cov pb2.cov
           cd ..
        fi
after_success:
  - cd python && coveralls && cd ..
